// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhtUg1ts9aKT3QMOUF5b0w0_NByFiUGNY',
    appId: '1:297156640459:web:f3d3509f655ccb3789254e',
    messagingSenderId: '297156640459',
    projectId: 'qizo2-c8f76',
    authDomain: 'qizo2-c8f76.firebaseapp.com',
    storageBucket: 'qizo2-c8f76.appspot.com',
    measurementId: 'G-P12QBSVMN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwXmq0GrWWjpFeh2rDIjdpbELbhtw6T80',
    appId: '1:297156640459:android:e1f0aa3616aae92f89254e',
    messagingSenderId: '297156640459',
    projectId: 'qizo2-c8f76',
    storageBucket: 'qizo2-c8f76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVaCr715giWG4OgR7oEDd4VnjMoCRJpYw',
    appId: '1:297156640459:ios:3811fb360b9e1e5d89254e',
    messagingSenderId: '297156640459',
    projectId: 'qizo2-c8f76',
    storageBucket: 'qizo2-c8f76.appspot.com',
    iosClientId: '297156640459-0s1qii0euvfjlhq73l6vmcmtvncqcorf.apps.googleusercontent.com',
    iosBundleId: 'com.example.qizo2',
  );
}
